-- Catalogue des listes curatées, éditable sans rebuild de l'app.
-- Lecture publique (anon + authenticated), écriture réservée au service role / dashboard.

create table public.curated_lists (
  id integer generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  description text not null default '',
  icon text not null default 'book-open',
  gradient_colors text[] not null default array['#D0DEF0','#8AACC8','#6B8EAD'],
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.curated_list_books (
  id bigint generated always as identity primary key,
  list_id integer not null references public.curated_lists(id) on delete cascade,
  isbn text not null,
  title text not null,
  author text not null default '',
  position integer not null default 0,
  unique (list_id, isbn)
);

create index curated_list_books_list_id_idx on public.curated_list_books (list_id);

alter table public.curated_lists enable row level security;
alter table public.curated_list_books enable row level security;

create policy "curated_lists_public_read"
  on public.curated_lists for select
  to anon, authenticated
  using (is_active);

create policy "curated_list_books_public_read"
  on public.curated_list_books for select
  to anon, authenticated
  using (exists (
    select 1 from public.curated_lists cl
    where cl.id = list_id and cl.is_active
  ));

-- Lecture seule côté client : aucun policy insert/update/delete.
revoke insert, update, delete on public.curated_lists from anon, authenticated;
revoke insert, update, delete on public.curated_list_books from anon, authenticated;
insert into public.curated_lists (id, title, subtitle, description, icon, gradient_colors, sort_order) values
  (1, 'Les classiques incontournables', 'Les œuvres qui ont marqué la littérature', 'Une sélection des chefs-d''œuvre littéraires que tout lecteur devrait découvrir au moins une fois.', 'landmark', array['#E8D5B7','#BFA57A','#9C8256'], 1),
  (2, 'SF : les voyages qui changent tout', 'Explorez des mondes extraordinaires', 'Les romans de science-fiction qui repoussent les frontières de l''imagination et questionnent notre humanité.', 'rocket', array['#B8C5E2','#8A9DC7','#6B7FAA'], 2),
  (3, 'Fierté française', 'Le meilleur de la littérature française', 'Les plumes françaises qui ont rayonné à travers le monde et continuent d''inspirer des générations de lecteurs.', 'pen-tool', array['#D0DEF0','#8AACC8','#6B8EAD'], 3),
  (4, 'Frissons garantis', 'Thrillers et polars à couper le souffle', 'Des intrigues haletantes, des rebondissements inattendus et des nuits blanches garanties.', 'search', array['#E8CACA','#C49090','#A67272'], 4),
  (5, 'Développement personnel', 'Transforme ta vie, un livre à la fois', 'Les livres qui changent les perspectives, développent la résilience et inspirent à devenir la meilleure version de soi.', 'brain', array['#D2E4D8','#8FB9A0','#6D9A80'], 5),
  (6, 'Tour du monde littéraire', 'Voyage à travers les cultures', 'Des romans du monde entier qui ouvrent des fenêtres sur des cultures et des réalités différentes.', 'globe-2', array['#D4E8E4','#89B8AD','#6A9B8F'], 6),
  (7, 'En moins de 200 pages', 'Des pépites courtes mais marquantes', 'Parfait pour une lecture rapide sans compromis sur la qualité. Des romans courts qui frappent fort.', 'zap', array['#E0D4E8','#A68CB8','#8B7099'], 7),
  (8, 'Livres à lire un soir de pluie', 'Lectures réconfortantes et atmosphériques', 'Des romans doux et enveloppants, parfaits pour se blottir sous un plaid quand la pluie tambourine aux carreaux.', 'cloud-rain', array['#D8E2EC','#9BB3C7','#7A96AC'], 8),
  (9, 'Les livres qui font pleurer', 'Les plus émouvants', 'Des histoires bouleversantes qui touchent en plein cœur. Préparez les mouchoirs.', 'heart-crack', array['#EDD8E4','#C499AE','#A67B90'], 9),
  (10, 'Fous rires garantis', 'Humour littéraire', 'Des livres hilarants qui donnent le sourire dès la première page. Idéal pour décompresser.', 'laugh', array['#F0E6C8','#D4C08A','#B8A46E'], 10),
  (11, 'Valise d''été', 'Lectures légères et addictives', 'Des page-turners parfaits pour la plage, le hamac ou le bord de la piscine. Impossible de les lâcher.', 'palmtree', array['#EDE0D0','#CAAE8E','#AD9272'], 11),
  (12, 'Ceux qu''on ne peut pas lâcher', 'Les page-turners absolus', 'Des livres impossibles à poser. Suspense, rebondissements et nuits blanches au programme.', 'flame', array['#DED0C4','#BDA48C','#A08A72'], 12),
  (13, 'Prix Nobel — les lauréats à lire', 'Un tour du monde et du siècle', '10 lauréats incontournables du prix Nobel de littérature, chacun d''une époque et d''un horizon différents.', 'award', array['#E8DCC8','#C4AE86','#A69368'], 13),
  (14, 'Vulgarisation scientifique', 'Comprendre le monde', 'Un livre par discipline pour explorer la science sans prise de tête. Du Big Bang aux maths en passant par l''évolution.', 'atom', array['#D0DFEE','#8AADC8','#6D90AA'], 14);

insert into public.curated_list_books (list_id, isbn, title, author, position) values
  (1, '9782070360024', 'L''Étranger', 'Albert Camus', 1),
  (1, '9782070408504', 'Le Petit Prince', 'Antoine de Saint-Exupéry', 2),
  (1, '9782070409228', 'Les Misérables', 'Victor Hugo', 3),
  (1, '9782070413119', 'Madame Bovary', 'Gustave Flaubert', 4),
  (1, '9782070360420', 'La Peste', 'Albert Camus', 5),
  (1, '9782253004226', 'Germinal', 'Émile Zola', 6),
  (1, '9782253006206', 'Le Rouge et le Noir', 'Stendhal', 7),
  (1, '9782253140870', 'L''Écume des jours', 'Boris Vian', 8),
  (1, '9782253007104', 'Les Fleurs du mal', 'Charles Baudelaire', 9),
  (1, '9782253196716', 'Le Comte de Monte-Cristo', 'Alexandre Dumas', 10),
  (2, '9782266320542', 'Dune', 'Frank Herbert', 1),
  (2, '9782070415731', 'Fahrenheit 451', 'Ray Bradbury', 2),
  (2, '9782070368228', '1984', 'George Orwell', 3),
  (2, '9782266283038', 'Le Meilleur des mondes', 'Aldous Huxley', 4),
  (2, '9782070360536', 'Fondation', 'Isaac Asimov', 5),
  (2, '9782070468751', 'Solaris', 'Stanislas Lem', 6),
  (2, '9782290308202', 'Neuromancien', 'William Gibson', 7),
  (2, '9782266230919', 'La Nuit des temps', 'René Barjavel', 8),
  (3, '9782070360024', 'L''Étranger', 'Albert Camus', 1),
  (3, '9782070379248', 'À la recherche du temps perdu', 'Marcel Proust', 2),
  (3, '9782070408504', 'Le Petit Prince', 'Antoine de Saint-Exupéry', 3),
  (3, '9782253008880', 'Les Trois Mousquetaires', 'Alexandre Dumas', 4),
  (3, '9782070413119', 'Madame Bovary', 'Gustave Flaubert', 5),
  (3, '9782070409228', 'Les Misérables', 'Victor Hugo', 6),
  (3, '9782070360284', 'Voyage au bout de la nuit', 'Louis-Ferdinand Céline', 7),
  (3, '9782253009009', 'Bel-Ami', 'Guy de Maupassant', 8),
  (3, '9782253004226', 'Germinal', 'Émile Zola', 9),
  (3, '9782253140870', 'L''Écume des jours', 'Boris Vian', 10),
  (4, '9782889730087', 'La Vérité sur l''affaire Harry Quebert', 'Joël Dicker', 1),
  (4, '9782253171676', 'Les Rivières pourpres', 'Jean-Christophe Grangé', 2),
  (4, '9782266254489', 'La Fille du train', 'Paula Hawkins', 3),
  (4, '9782253001171', 'Da Vinci Code', 'Dan Brown', 4),
  (4, '9782266207706', 'Ne le dis à personne', 'Harlan Coben', 5),
  (4, '9782330004996', 'Millénium 1 : Les hommes qui n''aimaient pas les femmes', 'Stieg Larsson', 6),
  (4, '9782253164913', 'Gone Girl', 'Gillian Flynn', 7),
  (4, '9782266208949', 'Le Silence des agneaux', 'Thomas Harris', 8),
  (4, '9782072764929', 'Chanson douce', 'Leïla Slimani', 9),
  (4, '9782290349311', 'Pars vite et reviens tard', 'Fred Vargas', 10),
  (5, '9782035969200', 'Atomic Habits', 'James Clear', 1),
  (5, '9782212567595', 'L''Art subtil de s''en foutre', 'Mark Manson', 2),
  (5, '9782892259551', 'Père riche, père pauvre', 'Robert Kiyosaki', 3),
  (5, '9782290020203', 'Le Pouvoir du moment présent', 'Eckhart Tolle', 4),
  (5, '9782290206058', 'Les 7 habitudes de ceux qui réalisent tout ce qu''ils entreprennent', 'Stephen R. Covey', 5),
  (5, '9782080700162', 'Pensées pour moi-même', 'Marc Aurèle', 6),
  (5, '9782266227926', 'Influence et manipulation', 'Robert Cialdini', 7),
  (5, '9782266286688', 'Ikigai', 'Héctor García & Francesc Miralles', 8),
  (5, '9782290258064', 'L''Alchimiste', 'Paulo Coelho', 9),
  (5, '9782253091752', 'Sapiens', 'Yuval Noah Harari', 10),
  (6, '9782020238113', 'Cent ans de solitude', 'Gabriel García Márquez', 1),
  (6, '9782070411726', 'Le Dieu des petits riens', 'Arundhati Roy', 2),
  (6, '9782253117957', 'Mémoires d''une geisha', 'Arthur Golden', 3),
  (6, '9782264043573', 'Les Cerfs-volants de Kaboul', 'Khaled Hosseini', 4),
  (6, '9782253044901', 'Le Parfum', 'Patrick Süskind', 5),
  (6, '9782253038047', 'La Maison aux esprits', 'Isabel Allende', 6),
  (6, '9782707306951', 'L''Amant', 'Marguerite Duras', 7),
  (6, '9782267021776', 'Le Livre de l''intranquillité', 'Fernando Pessoa', 8),
  (6, '9782070360079', 'Le Vieil Homme et la mer', 'Ernest Hemingway', 9),
  (6, '9782253060543', 'L''Amour aux temps du choléra', 'Gabriel García Márquez', 10),
  (7, '9782070360024', 'L''Étranger', 'Albert Camus', 1),
  (7, '9782070408504', 'Le Petit Prince', 'Antoine de Saint-Exupéry', 2),
  (7, '9782070462872', 'La Métamorphose', 'Franz Kafka', 3),
  (7, '9782070466634', 'Candide', 'Voltaire', 4),
  (7, '9782070360079', 'Le Vieil Homme et la mer', 'Ernest Hemingway', 5),
  (7, '9782072847134', 'L''Appel de la forêt', 'Jack London', 6),
  (7, '9782070364282', 'La Perle', 'John Steinbeck', 7),
  (7, '9782253064091', 'Le Prophète', 'Khalil Gibran', 8),
  (7, '9782070360109', 'La Chute', 'Albert Camus', 9),
  (7, '9782707306951', 'L''Amant', 'Marguerite Duras', 10),
  (8, '9782070440252', 'La Délicatesse', 'David Foenkinos', 1),
  (8, '9782253114864', 'L''Ombre du vent', 'Carlos Ruiz Zafón', 2),
  (8, '9782264053510', 'Le Cercle littéraire des amateurs d''épluchures de patates', 'Mary Ann Shaffer', 3),
  (8, '9782264044730', 'Kafka sur le rivage', 'Haruki Murakami', 4),
  (8, '9782266273374', 'La Librairie de l''île', 'Gabrielle Zevin', 5),
  (8, '9782266285025', 'Un appartement à Paris', 'Guillaume Musso', 6),
  (8, '9782020239301', 'Le Vieux qui lisait des romans d''amour', 'Luis Sepúlveda', 7),
  (8, '9782070439560', 'Persuasion', 'Jane Austen', 8),
  (8, '9782253155379', 'La Part de l''autre', 'Éric-Emmanuel Schmitt', 9),
  (8, '9782290238622', 'Stoner', 'John Williams', 10),
  (9, '9782811215576', 'Avant toi', 'Jojo Moyes', 1),
  (9, '9782253079910', 'Oscar et la dame rose', 'Éric-Emmanuel Schmitt', 2),
  (9, '9782264043573', 'Les Cerfs-volants de Kaboul', 'Khaled Hosseini', 3),
  (9, '9782266093088', 'La Chambre des officiers', 'Marc Dugain', 4),
  (9, '9782290343715', 'Ensemble, c''est tout', 'Anna Gavalda', 5),
  (9, '9782070408504', 'Le Petit Prince', 'Antoine de Saint-Exupéry', 6),
  (9, '9782266283304', 'Nos étoiles contraires', 'John Green', 7),
  (9, '9782330013073', 'La Couleur des sentiments', 'Kathryn Stockett', 8),
  (9, '9782253117186', 'Un secret', 'Philippe Grimbert', 9),
  (9, '9782757828960', 'Moi d''abord', 'Katherine Pancol', 10),
  (10, '9782070437436', 'Le Guide du voyageur galactique', 'Douglas Adams', 1),
  (10, '9782253124054', 'Au secours pardon', 'Frédéric Beigbeder', 2),
  (10, '9782012101333', 'Astérix le Gaulois', 'Goscinny & Uderzo', 3),
  (10, '9782290077252', 'Le Journal de Bridget Jones', 'Helen Fielding', 4),
  (10, '9782070315734', '99 francs', 'Frédéric Beigbeder', 5),
  (10, '9782266218528', 'Le Vieux qui ne voulait pas fêter son anniversaire', 'Jonas Jonasson', 6),
  (10, '9782253009009', 'Bel-Ami', 'Guy de Maupassant', 7),
  (10, '9782253012740', 'Les Tribulations d''un Chinois en Chine', 'Jules Verne', 8),
  (10, '9782253111184', 'Hygiène de l''assassin', 'Amélie Nothomb', 9),
  (10, '9782020363761', 'Le Monde selon Garp', 'John Irving', 10),
  (11, '9782290258064', 'L''Alchimiste', 'Paulo Coelho', 1),
  (11, '9782889730087', 'La Vérité sur l''affaire Harry Quebert', 'Joël Dicker', 2),
  (11, '9782253073697', 'Big Little Lies', 'Liane Moriarty', 3),
  (11, '9782266276252', 'Et après…', 'Guillaume Musso', 4),
  (11, '9782330004996', 'Millénium 1 : Les hommes qui n''aimaient pas les femmes', 'Stieg Larsson', 5),
  (11, '9782253126300', 'Mange, prie, aime', 'Elizabeth Gilbert', 6),
  (11, '9782072965821', 'L''Anomalie', 'Hervé Le Tellier', 7),
  (11, '9782266290609', 'Où es-tu ?', 'Marc Levy', 8),
  (11, '9782264073105', 'Eleanor Oliphant va très bien', 'Gail Honeyman', 9),
  (11, '9782330037437', 'Un été sans les hommes', 'Siri Hustvedt', 10),
  (12, '9782253164913', 'Gone Girl', 'Gillian Flynn', 1),
  (12, '9782253001171', 'Da Vinci Code', 'Dan Brown', 2),
  (12, '9782743614812', 'Shutter Island', 'Dennis Lehane', 3),
  (12, '9782266254489', 'La Fille du train', 'Paula Hawkins', 4),
  (12, '9782266320542', 'Dune', 'Frank Herbert', 5),
  (12, '9782266207706', 'Ne le dis à personne', 'Harlan Coben', 6),
  (12, '9782253196716', 'Le Comte de Monte-Cristo', 'Alexandre Dumas', 7),
  (12, '9782266274500', 'Divergente', 'Veronica Roth', 8),
  (12, '9782253044901', 'Le Parfum', 'Patrick Süskind', 9),
  (12, '9782253067986', 'Rebecca', 'Daphné du Maurier', 10),
  (13, '9782070360024', 'L''Étranger', 'Albert Camus', 1),
  (13, '9782020238113', 'Cent ans de solitude', 'Gabriel García Márquez', 2),
  (13, '9782070360079', 'Le Vieil Homme et la Mer', 'Ernest Hemingway', 3),
  (13, '9782264047960', 'Beloved', 'Toni Morrison', 4),
  (13, '9782253030737', 'Pays de neige', 'Yasunari Kawabata', 5),
  (13, '9782253067900', 'La Végétarienne', 'Han Kang', 6),
  (13, '9782253063193', 'Les Buddenbrook', 'Thomas Mann', 7),
  (13, '9782070336876', 'La Place', 'Annie Ernaux', 8),
  (13, '9782020403436', 'L''Aveuglement', 'José Saramago', 9),
  (13, '9782070373581', 'Rue des Boutiques Obscures', 'Patrick Modiano', 10),
  (14, '9782080297136', 'Une brève histoire du temps', 'Stephen Hawking', 1),
  (14, '9782253091752', 'Sapiens : Une brève histoire de l''humanité', 'Yuval Noah Harari', 2),
  (14, '9782290130902', 'L''Univers à portée de main', 'Christophe Galfard', 3),
  (14, '9782738112439', 'Le Gène égoïste', 'Richard Dawkins', 4),
  (14, '9782501006286', 'Cosmos', 'Carl Sagan', 5),
  (14, '9782290225790', 'Le Théorème du parapluie', 'Mickaël Launay', 6),
  (14, '9782080244987', 'La Théorie du chaos', 'James Gleick', 7),
  (14, '9782290141809', 'Le Grand Roman des maths', 'Mickaël Launay', 8),
  (14, '9782100791729', 'Pourquoi E=mc² ?', 'Brian Cox & Jeff Forshaw', 9),
  (14, '9782081343016', 'Et si… ?', 'Randall Munroe', 10);
-- Aligne la séquence après le seed à ids manuels
select setval(pg_get_serial_sequence('public.curated_lists', 'id'), (select max(id) from public.curated_lists));

-- Intégrité rétroactive des tables d'interaction utilisateur
alter table public.user_saved_curated_lists
  add constraint user_saved_curated_lists_list_id_fkey
  foreign key (list_id) references public.curated_lists(id) on delete cascade;

alter table public.user_curated_book_reads
  add constraint user_curated_book_reads_list_id_fkey
  foreign key (list_id) references public.curated_lists(id) on delete cascade;

create index if not exists user_saved_curated_lists_list_id_idx on public.user_saved_curated_lists (list_id);
create index if not exists user_curated_book_reads_list_id_idx on public.user_curated_book_reads (list_id);
